### ISSUE TITLE
T-Online show numbers from Outlook XML DPI fix

### ISSUE THREAD

**Issue by M-J-Robbins** [hteumeuleu/email-bugs#83]
The XML fix for DPI scaling in Outlook looks like this.
```  
<!--[if mso]>
  <xml>
  <o:OfficeDocumentSettings>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
  </xml>
  <![endif]-->
```

In T-Online this shows the number `96` at the top of the email. 

I've found a fix by wrapping the `<xml>` in `<noscript>`.  Noscript will render in Outlook but not in -T-Online so the `96` gets hidden from T-online and the XML fix is still applied in Outlook.

```
<!--[if mso]>
<noscript>
  <xml>
    <o:OfficeDocumentSettings>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
  </xml>
</noscript>
<![endif]-->
```

**Comment by hteumeuleu** [comment]
Clever solution, Mark! This used to happen in Orange's mobile webmail in France (but was fixed a year or so ago). Never thought about using noscript like this. Thanks!

**Comment by hteumeuleu** [comment]
I can’t seem to reproduce this bug anymore. Here’s the code I sent using Putsmail:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>OfficeDocumentSettings</title>
	<!--[if mso]>
	<xml>
	<o:OfficeDocumentSettings>
	<o:PixelsPerInch>96</o:PixelsPerInch>
	</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->
</head>
<body>
	<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam, quam.</p>
</body>
</html>
```

@M-J-Robbins can you confirm?

**Comment by husseinalhammad** [comment]
I don't see the `96` at the top either, but I see #43 (T-online.de webmail renders conditional comments) is still an issue in general.

**Comment by M-J-Robbins** [comment]
I've lost access to my test account but Litmus is showing it working fine now 👍

**Comment by hteumeuleu** [comment]
Awesome! I'm closing this!
